[project]
name = "test_serial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "setteZ", email = "furgorsin@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pyserial>=3.5",
]

[project.scripts]
ts = "test_serial:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
